//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProExam.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    
    public partial class Question
    {
        public int Quest_id { get; set; }

        [AllowHtml]
        public string Quest_content { get; set; }

        [AllowHtml]
        public string Ans_a { get; set; }

        [AllowHtml]
        public string Ans_b { get; set; }

        [AllowHtml]
        public string Ans_c { get; set; }

        [AllowHtml]
        public string Ans_d { get; set; }

        public string correct_ans { get; set; }
        public string Subject_id { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
